apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/slavic-viking/oca-argo-cd.git
    targetRevision: main
    kustomize:
      images:
      - slavicviking/k8s-demo-app:a7cb10ddcc12a9e9c008228f209066850df3ebd7
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
