apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-user
  namespace: monitoring
spec:
  encryptedData:
    password: AgBIcsuonFT1pGRPznWWkIprCbwgLCfiSQGYfVNYZsu6t3eOy4nuugmuM3EwSrr/ZKYnqn7B2IWs5bShn4sQ336aX/y+GWnZ2ywIGDZW3FeR14fwYrol/XQebA80SbartuhaABclg6S7aHTsDGSefJsdG1sN4NZJ+S+wGy98lWWIKSR4YyiMOQ3RZ4wuLjHNJ3WGNx4Wked0ikfiUswLbGOJckyBqUo6/z2wbxOcKjNP2ZQnOrw7xG5kqRqe9sasTESjmyr7ci3eQy2UCvw6+sZZ3RF41iNbwUmgUF8O2BtXXgjOPo3Tw/6Rnpi8WEa8014qweFl9ZwnL65Zgy1tKQULFnRHVKeTyv96SSCsbC8LeIOJ0GCX1E4b+3fORRrxHrS/Np4xLS5VnAH2i4kjJw90bzsCg684KAeC9vYgqwp/v7mEZcVyNWRCm5ZDtIyaW61Dw4/MjWXNKgVA/S0fe9MtIA9nnQdHkHtlM//UdbwvbkpDhPuCyZQdC51g1diky5caCxFK9uTLa1hF6lg+x5aPK5tZwnTg76tf9OPUvB/psUklAHQYkszsHVDkfOpE5UfbD+PnoG3lN9EkcyRCrHXjUwpZJBpZQzr/SzR3kNig6Hw16lIMEnvhYR6s6vRZ5MJ7YA/j7GGnIsTzYDYAFoCzH64K4FM8RfzUehFzatSIomEs2TEilk4809DFsomEL6nrTJ6Gjxt3lKpw69EVS7rk/Lnl/UY=
    username: AgDJ28mbB41NPLmnwvt8X2dmYn2QvcinG58GYciIaKKmHGh6lneL2noEVx5cg+4u0Z+Fr+Uto3z8m2W5lbNKOtb5+m+y00moO4RSb6wTxuLBFQ/iSEV12qZ20Hxs8oANd1bKV6xMPH7I66mOVKtE6Ys/ExgBD2OtPbZJWn96iOj2jeykiH2ubO2dEWxHgRY4iDbeqiNBNJ3W2g9i+Z5KPWWApCRUI3pwnexOKgk6njfsnv1wPr4OfWYZi4NHgrEY7Wq+A4FLvCb7CdZZzW+kKVlDd+C4s9uVHTlIbW7Q62QHWOm28EkjTHTKF8iUYvwcGFtJfpbY+yTJSZ+wfQqow7l4HMGH4LQsmsokJlE9N67vzpuMbd2OLOLerScszWG4J3mQSyrWG8Ki5RjwD8qaTL7dGWrA7/nkKSOwwqM/STzj5NlBn1kyXCAfOsKbpHYGQMqb8BD9+Lzs8WGF8ZHrEISEIzp2/J2hCKASO32mM0mn79qaYfxneasUS+CX86rTJdsMy6THlcFAWcYA2aYG29mic6kYEdGWTn0rlQnDkEhwdeNgc9uVLZwziEJlwAE5vEHawskY7wMH/W3ZtYUXuH0znz/bqpoOp3HAXhqxygsRVfDTVZpJkOpsmLmAsuwLJgCREqGfDAQgk6+zc2/EbXEmbskzL61w5v9Qsyqomkgz1WVkXf5P1BT4b90jlEjviveiJ6QPZ6iKzP6NeKg/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-user
      namespace: monitoring

